% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Permutation Tests},
  pdfauthor={Livio Finos},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Permutation Tests}
\author{Livio Finos}
\date{University of Padova}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Introduction}\label{introduction}

\subsection{Introduction}\label{introduction-1}

\begin{itemize}
\tightlist
\item
  Well-established nonparametric inference approach: Fisher (1935);
  Pitman (1937, 1938).\\
\item
  Generally requires fewer assumptions about the data generating process
  than parametric counterparts.\\
\item
  Excellent inferential properties, typically:

  \begin{itemize}
  \tightlist
  \item
    Exactness (exact control of Type I error)
  \item
    Asymptotic optimality and convergence to parametric counterparts
    when they exist.
  \end{itemize}
\end{itemize}

\begin{itemize}
\tightlist
\item
  Fisher's exact test is a prototypical example, but
\item
  The general approach had limited applicability without computational
  support.
\end{itemize}

\subsection{Renewed Interest in Permutation
Testing}\label{renewed-interest-in-permutation-testing}

\begin{itemize}
\tightlist
\item
  A milestone: Westfall and Young (1993). \emph{Resampling-Based
  Multiple Testing: Examples and Methods for p-value Adjustment}. Wiley.
\item
  Many active research areas adopt these methods in daily statistical
  analysis (e.g., genetics and neuroscience: Nichols and Holmes (2002);
  Pantazis et al.~(2009); Winkler et al.~(2014)).\\
\item
  Permutation approach:

  \begin{itemize}
  \tightlist
  \item
    Ideal for \textbf{randomized experimental designs}\\
  \item
    Handles complex models without formal definition of the data
    generating process.
  \end{itemize}
\end{itemize}

\subsection{\texorpdfstring{The \texttt{flip}
Package}{The flip Package}}\label{the-flip-package}

Available on CRAN and GitHub (\url{https://github.com/livioivil/flip}).

To install the GitHub version in R:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(devtools)}
\FunctionTok{install\_github}\NormalTok{(}\StringTok{\textquotesingle{}livioivil/flip\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\textbf{Before starting}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Clean memory}
\FunctionTok{rm}\NormalTok{(}\AttributeTok{list =} \FunctionTok{ls}\NormalTok{())}

\CommentTok{\# Customize graph output}
\NormalTok{par.old }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{()}
\FunctionTok{par}\NormalTok{(}\AttributeTok{cex.main =} \FloatTok{1.5}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{, }\AttributeTok{col =} \StringTok{"darkgrey"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{20}\NormalTok{, }\AttributeTok{cex =} \DecValTok{3}\NormalTok{)}
\FunctionTok{palette}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#FF0000"}\NormalTok{, }\StringTok{"\#00A08A"}\NormalTok{, }\StringTok{"\#FFCC00"}\NormalTok{, }\StringTok{"\#445577"}\NormalTok{, }\StringTok{"\#45abff"}\NormalTok{))}

\CommentTok{\# Customize knitr output}
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}\AttributeTok{fig.align =} \StringTok{"center"}\NormalTok{)  }\CommentTok{\# fig.width=6, fig.height=6}
\end{Highlighting}
\end{Shaded}

\subsection{The Age vs Reaction Time
Dataset}\label{the-age-vs-reaction-time-dataset}

Subjects' reaction times were tested by having them grab a meter stick
after it was released. The number of centimeters the meter stick dropped
before being caught directly measures response time.

\texttt{Age} values are in years. \texttt{Gender} is coded as \texttt{F}
for female and \texttt{M} for male. \texttt{Reaction.Time} values are in
centimeters.

(Data are fictitious)

To read the data:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(reaction, }\AttributeTok{package =} \StringTok{"flip"}\NormalTok{)}
\CommentTok{\# Alternatively, download from: https://github.com/livioivil/flip/tree/master/data}
\CommentTok{\# or load("reaction.rda")}
\FunctionTok{str}\NormalTok{(reaction)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Classes 'tbl_df', 'tbl' and 'data.frame':    10 obs. of  3 variables:
##  $ Age          : num  70 50 30 60 80 60 30 30 20 50
##  $ Gender       : Factor w/ 2 levels "F","M": 1 1 2 1 2 1 2 2 1 2
##  $ Reaction.Time: num  28.7 20.4 11.6 22.3 26.5 ...
\end{verbatim}

Plot the data:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x =}\NormalTok{ reaction}\SpecialCharTok{$}\NormalTok{Age, }\AttributeTok{y =}\NormalTok{ reaction}\SpecialCharTok{$}\NormalTok{Reaction.Time, }\AttributeTok{pch =} \DecValTok{20}\NormalTok{, }\AttributeTok{col =} \DecValTok{2}\NormalTok{, }\AttributeTok{cex =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-4-1} \end{center}

\subsection{Measuring Dependence Between Two
Variables}\label{measuring-dependence-between-two-variables}

Define: - \(X = Age\)\\
- \(Y = Reaction.Time\)

Review common indices for measuring (linear) dependence between two
variables.

\subsubsection{Covariance and Variance}\label{covariance-and-variance}

\textbf{Covariance} between \(X\) and \(Y\):

\(\sigma_{xy} = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{n}\)

\begin{itemize}
\tightlist
\item
  Values between \(-\infty\) and \(\infty\)\\
\item
  \(\sigma_{xy} \approx 0\): No dependency between \(X\) and \(Y\)\\
\item
  \(\sigma_{xy} \gg 0\) (\(\ll 0\)): Strong positive (negative)
  dependency
\end{itemize}

\textbf{Variance} of \(X\):

\(\sigma_{xx} = \sigma_x^2 = \frac{\sum_{i=1}^n (x_i - \bar{x})^2}{n}\)

\textbf{Standard Deviation} of \(X\):

\(\sigma_x = \sqrt{\sigma_{xx}}\)

\subsubsection{Correlation}\label{correlation}

Covariance alone makes it difficult to assess relationship strength.
Note that:

\(-\sigma_x \sigma_y \leq \sigma_{xy} \leq \sigma_x \sigma_y\)

is equivalent to:

\(-1 \leq \frac{\sigma_{xy}}{\sigma_x \sigma_y} \leq 1\)

\textbf{Correlation} between \(X\) and \(Y\):

\(\rho_{xy} = \frac{\sigma_{xy}}{\sigma_x \sigma_y} = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum_{i=1}^n (x_i - \bar{x})^2} \sqrt{\sum_{i=1}^n (y_i - \bar{y})^2}}\)

\begin{itemize}
\tightlist
\item
  Values between \(-1\) and \(1\)
\item
  \(\rho_{xy} \approx 0\): No dependency
\item
  \(\rho_{xy} \approx 1\) (\(-1\)): Strong positive (negative)
  dependency
\end{itemize}

\subsubsection{Linear Trend: Least Squares
Method}\label{linear-trend-least-squares-method}

Describe the relationship between \texttt{Reaction.Time} and
\texttt{Age} with a straight line:

\(E(Reaction.Time) \approx \beta_0 + \beta_1 Age\)\\
\(E(Y) = \beta_0 + \beta_1 X\)

Draw a line through the center of the data.

\textbf{Least-squares estimator}: Find parameters minimizing the sum of
squared residuals:

Find \(\hat{\beta}_0\) and \(\hat{\beta}_1\) that minimize:
\(\sum_{i=1}^n (y_i - (\hat{\beta}_0 + \hat{\beta}_1 x_i))^2\)

Estimates:\\
- Slope:
\(\hat{\beta}_1 = \frac{\sigma_{xy}}{\sigma_{xx}} = \rho_{xy}\frac{\sigma_y}{\sigma_x} = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^n (x_i - \bar{x})^2} =\)
0.2064719\\
- Intercept: \(\hat{\beta}_0 = \bar{y} - \hat{\beta}_1\bar{x} =\)
10.3013483 - Estimated response:
\(\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 x_i\) - Residuals:
\(y_i - (\hat{\beta}_0 + \hat{\beta}_1 x_i) = y_i - \hat{y}_i\)

Sum of squared residuals:
\(\sum_{i=1}^n (y_i - \hat{\beta}_0 - \hat{\beta}_1 x_i)^2 = \sum_{i=1}^n (y_i - \hat{y}_i)^2\)

Visual representation:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{data =}\NormalTok{ reaction)}
\FunctionTok{coefficients}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)         Age 
##  10.3013483   0.2064719
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(reaction}\SpecialCharTok{$}\NormalTok{Age, reaction}\SpecialCharTok{$}\NormalTok{Reaction.Time, }\AttributeTok{pch =} \DecValTok{20}\NormalTok{, }\AttributeTok{col =} \DecValTok{2}\NormalTok{, }\AttributeTok{cex =} \DecValTok{1}\NormalTok{)}
\NormalTok{coeff }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(}\FunctionTok{coefficients}\NormalTok{(model), }\DecValTok{1}\NormalTok{)}
\FunctionTok{title}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Y ="}\NormalTok{, coeff[}\DecValTok{1}\NormalTok{], }\StringTok{"+"}\NormalTok{, coeff[}\DecValTok{2}\NormalTok{], }\StringTok{"* X"}\NormalTok{))}
\FunctionTok{abline}\NormalTok{(model, }\AttributeTok{col =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-7-1} \end{center}

\section{Permutation Approach to Hypothesis
Testing}\label{permutation-approach-to-hypothesis-testing}

\subsubsection{Preliminary Remarks}\label{preliminary-remarks}

Note that all measures above make no assumptions about the random
process generating the data.

Now assume \(Y\) (and possibly \(X\)) is generated by a random variable.
Further minimal assumptions will be specified later.

\textbf{Question: Is there a relationship between \(Y\) and \(X\)?}

We estimated \(\hat{\beta}_1 =\) 0.2064719

But is the \textbf{true value} \(\beta_1\) actually different from 0
(indicating no relationship)? Or is the difference from 0 due to random
sampling?

\begin{itemize}
\item
  \textbf{Null Hypothesis} \(H_0: \beta_1 = 0\) (the \textbf{true}
  \(\beta_1\), not its estimate \(\hat{\beta}_1\)!). No relationship
  between \(X\) and \(Y\).
\item
  \textbf{Alternative Hypothesis} \(H_1: \beta_1 > 0\) (positive
  relationship).
\end{itemize}

Other possible \(H_1\) specifications: \(\beta_1 < 0\) or, more
commonly, \(\beta_1 \neq 0\).

\subsection{Permutation Tests in a
Nutshell}\label{permutation-tests-in-a-nutshell}

As a toy example, use a data subset:

\begin{verbatim}
##   Age Gender Reaction.Time
## 2  50      F         20.42
## 3  30      M         11.62
## 4  60      F         22.27
\end{verbatim}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-8-1} \end{center}

\begin{itemize}
\tightlist
\item
  \emph{If \(H_0\) is true}: No linear relationship between \(X\) and
  \(Y\)
\item
  Observed trend is due to chance
\item
  Any other pairing of \(x_i\) and \(y_i\) was equally likely
\item
  Generate hypothetical datasets by permuting \(Y\) observations
\item
  How many equally likely datasets exist with observed \(X\) and \(Y\)?
  \(3 \times 2 \times 1 = 3! = 6\) possible datasets.
\end{itemize}

\textbf{Remark}: We only assume \(Y\) is a random variable. The key
assumption is exchangeability: the joint density \(f(y_1,\ldots,y_n)\)
is invariant to permutations of \(y_1,\ldots,y_n\).

\subsubsection{All Potential Datasets}\label{all-potential-datasets}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-9-1} \end{center}

\paragraph{In Our Complete Dataset}\label{in-our-complete-dataset}

Apply the same principle to the full dataset\ldots{}

How many permutations of \(y_1,\ldots,y_n\) are possible?
\(n! = 10! = 3,628,800\).

Manageable, but with \(n = 20\)? \(20! = 2.43 \times 10^{18}\) - too
large!

Calculate a smaller but sufficiently large number \(B\) of random
permutations.

Examples:

\textbf{\texttt{Age} vs Permuted \texttt{Reaction.Time}}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-10-1} \end{center}

Repeat 5000 times and examine the \(\hat{\beta}_1\) histogram:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# beta\_1 estimated on observed data}
\NormalTok{beta1 }\OtherTok{\textless{}{-}} \FunctionTok{coefficients}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{data =}\NormalTok{ reaction))[}\DecValTok{2}\NormalTok{]}

\CommentTok{\# Function to permute y and calculate beta\_1}
\NormalTok{my.beta.perm }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(Y, X) \{}
\NormalTok{  model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\FunctionTok{sample}\NormalTok{(Y) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X)}
  \FunctionTok{coefficients}\NormalTok{(model)[}\DecValTok{2}\NormalTok{]}
\NormalTok{\}}

\CommentTok{\# Replicate B{-}1 times}
\NormalTok{beta.perm }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(B, }\FunctionTok{my.beta.perm}\NormalTok{(reaction}\SpecialCharTok{$}\NormalTok{Reaction.Time, reaction}\SpecialCharTok{$}\NormalTok{Age))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-13-1} \end{center}

\subsubsection{\texorpdfstring{How Likely Was
\(\hat{\beta}_1 ^{obs}\)?}{How Likely Was \textbackslash hat\{\textbackslash beta\}\_1 \^{}\{obs\}?}}\label{how-likely-was-hatbeta_1-obs}

(before the experiment!)

What was the probability of obtaining a value
\(\geq \hat{\beta}_1 ^{obs}\) among possible \(\hat{\beta}_1 ^{*b}\)
values (from permuted data)?

Remarks: - \(\hat{\beta}_1 ^{*b} < \hat{\beta}_1 ^{obs}\) (closer to 0):
Less evidence against \(H_1\) than \(\hat{\beta}_1 ^{obs}\) -
\(\hat{\beta}_1 ^{*b} \geq \hat{\beta}_1 ^{obs}\): Equal or stronger
evidence for \(H_1\) than \(\hat{\beta}_1 ^{obs}\)

\subsubsection{P-value Calculation}\label{p-value-calculation}

Out of B = 5000 permutations, we obtained 4921 cases where
\(\hat{\beta}_1 ^{*b} \leq \hat{\beta}_1 ^{obs}\).

The p-value (significance) is:
\(p = \frac{\#(\hat{\beta}_1 ^{*b} \geq \hat{\beta}_1 ^{obs})}{B} =\)
0.0162

(\(\hat{\beta}_1 ^{obs}\) counts as one random permutation)

\subsubsection{Interpretation}\label{interpretation}

The probability \(P(\hat{\beta}_1^* \geq \hat{\beta}_1 =\) 0.206
\(| H_0) = p =\) 0.0162 is very small. It was unlikely to obtain such a
value \textbf{if \(H_0\) is true}.

The Neyman-Pearson approach established significance thresholds like
\(\alpha = .05\) (or \(= .01\)). When \(p \leq \alpha\), we reject
\(H_0\) (no relationship). We then conclude \(H_1\) is likely true
(positive relationship).

\begin{itemize}
\tightlist
\item
  Type I error: False Positive\\
  True hypothesis is \(H_0\) (no correlation), but we accept \(H_1\)
  (positive correlation)
\item
  Type II error: False Negative\\
  True hypothesis is \(H_1\) (positive correlation), but we fail to
  reject \(H_0\) (no correlation)
\end{itemize}

\subsection{Summary}\label{summary}

\textbf{p-value}: Proportion of experiments providing equal or stronger
evidence against \(H_0\) compared to observed data.

To compute it, we need: - \textbf{Orbit \(\mathcal{O}\)} - \textbf{Test
statistic} (\(T: \mathbb{R}^n \to \mathbb{R}\)) quantifying evidence
against \(H_0\) - Higher values indicate stronger evidence against
\(H_0\) - Computing \(T\) for each \(\mathcal{O}\) element induces an
ordering on \(\mathcal{O}\)

In our example:
\(T = \hat{\beta}_1 = \hat{\sigma}_{xy}/\hat{\sigma}_{xx}\) (estimated
slope). Higher slope indicates stronger evidence for \(H_1\).

\textbf{Type I Error Control}

We want to limit false discoveries (be conservative). Bound the
probability of false discovery:

\(P(\text{p-value} \leq \alpha | H_0) \leq \alpha\)

This ensures that over many experiment replications, we find false
correlations with probability \(\alpha\) (e.g., \(0.05 = 5\%\)).

\subsubsection{\texorpdfstring{Implementation in
\texttt{flip}}{Implementation in flip}}\label{implementation-in-flip}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(flip)}
\NormalTok{(res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{tail =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##               Test  Stat tail p-value
## Reaction.Time    t 2.633    >  0.0150
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compare with:}
\CommentTok{\# flip(Reaction.Time \textasciitilde{} Age, data = reaction, tail = 1, statTest = "cor")}
\CommentTok{\# flip(Reaction.Time \textasciitilde{} Age, data = reaction, tail = 1, statTest = "coeff")}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-15-1} \end{center}

\textbf{Type I Error Control}

We want to guarantee few false positives. Bound false discovery
probability:

\(P(\text{p-value} \leq \alpha | H_0) \leq \alpha\)

This ensures long-run false correlation discovery rate \(\leq \alpha\)
(e.g., 5\%).

\subsubsection{Two-sided Alternatives}\label{two-sided-alternatives}

\(H_1: \beta_1 > 0\) (positive relationship) requires a priori
justification.

More commonly, the two-sided alternative is appropriate:
\(H_1: \beta_1 \neq 0\) (relationship exists, direction unspecified)

We consider both very small and very large estimated coefficients as
anomalous (`far from 0').

P-value:
\(p = \frac{\#(|\hat{\beta}_1^{*b}| \geq |\hat{\beta}_1^{obs}|)}{B} =\)
0.0326

(Note: observed test statistic included among permutations)

In \texttt{flip}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(flip)}
\NormalTok{(res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{tail =} \DecValTok{0}\NormalTok{, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##               Test  Stat tail p-value
## Reaction.Time    t 2.633   ><  0.0374
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-17-1} \end{center}

\subsection{A More Formal Approach}\label{a-more-formal-approach}

(See also Pesarin, 2001;
\href{https://link.springer.com/content/pdf/10.1007/s11749-017-0571-1.pdf}{Hemerik
\& Goeman, 2018})

Let \(Y\) be data in sample space \(\mathcal{Y}\). Let \(\Pi\) be a
(usually finite) set of transformations
\(\pi: \mathcal{Y} \to \mathcal{Y}\) forming a \textbf{group} under
composition: - Contains identity - Every element has an inverse -
Closed: if \(\pi_1, \pi_2 \in \Pi\), then \(\pi_1 \circ \pi_2 \in \Pi\)

(e.g., \(\Pi\) = all possible permutations)

\textbf{Null Hypothesis}\\
\(H_0: Y \sim P \in \Omega_0\)

\textbf{Randomization Hypothesis} Under \(H_0\), the distribution of
\(Y\) is invariant under \(\Pi\): for every \(\pi \in \Pi\), \(\pi Y\)
and \(Y\) have the same distribution when \(Y \sim P \in \Omega_0\).

(See also Lehmann \& Romano, 2006. \emph{Testing Statistical
Hypotheses}. Springer.)

\textbf{Test statistic} \(T(Y): \mathbb{R}^n \to \mathbb{R}\)

\(T^{(k)}(Y)\) is the \(\lceil(1-\alpha)|\Pi|\rceil\)-th sorted value of
\(T(\pi Y)\)

Define the test: \[
\phi(Y) = 
\begin{cases} 
1 & \text{if } T(Y) > T^{(k)}(Y) \\
0 & \text{otherwise}
\end{cases}
\]

\textbf{Theorem}: Under \(H_0\), \(E_P(\phi(Y)) = \alpha\), i.e.,
\(P(T(Y) > T^{(k)}) \leq \alpha\).

\textbf{Proof}

For each \(Y \in \mathcal{Y}\), define orbit
\(O_Y = \{\pi Y : \pi \in \Pi\} \subseteq \mathcal{Y}\).

Let \(A = \{Y \in \mathcal{Y} : T(Y) > T^{(k)}(Y)\}\) be the rejection
set. Under \(H_0\), by group structure, \(\Pi\pi = \Pi\) for all
\(\pi \in \Pi\), so \(T^{(k)}(\pi Y) = T^{(k)}(Y)\) for all
\(\pi \in \Pi\). Thus: \[
\#\{\pi \in \Pi : \pi Y \in A\} = \#\{\pi \in \Pi : T(\pi Y) > T^{(k)}(\pi Y)\} = \#\{\pi \in \Pi : T(\pi Y) > T^{(k)}(Y)\} \leq \alpha |O_Y|
\]

Endow orbits with inherited \(\sigma\)-algebra. As in Lehmann (2005,
Theorem 15.2.2): \[
P(Y \in A | O_Y) = \frac{|A|}{|O_Y|}
\] Bounded by \(\alpha\). Hence: \[
P(Y \in A) = \mathbb{E}\{P(Y \in A | O_Y)\} \leq \alpha
\]

\textbf{Alternative Proof}

By construction, \(\sum_{\pi \in \Pi} \phi(\pi Y) = |\Pi|\alpha\). Thus:
\[
|\Pi|\alpha = E_P\left(\sum_{\pi \in \Pi} \phi(\pi Y)\right) = \sum_{\pi \in \Pi} E_P(\phi(\pi Y))
\]

By null hypothesis: \(E_P(\phi(Y)) = E_P(\phi(\pi Y))\), so: \[
|\Pi|\alpha = \sum_{\pi \in \Pi} E_P(\phi(Y)) = |\Pi| E_P(\phi(Y))
\] giving \(E_P(\phi(Y)) = \alpha\).

\subsubsection{Further Notes on Permutation
Testing}\label{further-notes-on-permutation-testing}

\textbf{Orbit}:
\(\mathcal{O} = \{\pi Y : \pi \in \Pi\} \subseteq \mathcal{Y}\)

i.e.~\(\mathcal{O} = \{\text{all permutations of observed data } \mathbf{y}\} = \{\mathbf{y}^*: \pi^* \circ \mathbf{y}\}\)

\paragraph{Exchangeability}\label{exchangeability}

\textbf{Exchangeability Assumption}: Under \(H_0\), observations are
exchangeable: e.g., \(f(y_1, y_2) = f(y_2, y_1)\).

Therefore the \(\mathcal{O}\) is a set of samples in \(\mathcal{Y}\)
sharing the same likelihood under the null hypothesis:
\(\mathcal{O} = \{\pi \mathbf{y}: f_{H_0}(\pi \mathbf{y}) = f_{H_0}(\mathbf{y})\}\)

(\(|\mathcal{O}|\) = number of elements)

With exchangeability:

\textbf{Proof Intuition} (alternative Type I error control proof):

\[
f(\mathbf{y}|\mathcal{O}) = \frac{f(\mathbf{y} \cap \mathcal{O})}{f(\mathcal{O})} = \frac{f(\mathbf{y})}{f(\mathcal{O})} = \frac{f(\mathbf{y})}{f(\cup_{y \in \mathcal{O}} y)} = \frac{1}{|\mathcal{O}|} \ \forall \ \mathbf{y} \in \mathcal{O}
\] Each permutation is equally likely in \(\mathcal{O}\) (due to group
structure).

\[
\begin{aligned}
E(\phi(Y)|\mathbf{y} \in \mathcal{O}, H_0) &= P(T(\mathbf{y}) > T^{(k)} | \mathbf{y} \in \mathcal{O}, H_0) \\
&= \int_{T^{(k)}}^{+\infty} f(T(\mathbf{y})) dT(\mathbf{y}) \\
&= \sum_{\mathbf{y} \in \mathcal{O}} I(T(\mathbf{y}) > T^{(k)})/|\mathcal{O}| \leq \alpha \quad \forall \mathcal{O}
\end{aligned}
\]

Then:
\(E(\phi(\mathbf{y})) = \int_P E(\phi(\mathbf{y})|\mathbf{y} \in \mathcal{O}, H_0) d\mathbf{y}\)

\paragraph{Independence vs
exchangeability}\label{independence-vs-exchangeability}

Always true if observations:\\
- Are \textbf{identically distributed} - Have \textbf{same dependence}
(e.g., same correlation)

Parametric \(t\)-tests and linear models assume independence (stricter
than `same dependence') and normality of errors---more stringent than
permutation approach.

When normality fails, parametric approaches only provide asymptotic Type
I error control, while permutation provides exact control.

\subsubsection{Properties (see Pesarin,
2001)}\label{properties-see-pesarin-2001}

The theorem proves permutation tests have \textbf{exact Type I error
control}: \(P(\text{p-value} \leq \alpha | H_0) = \alpha\), assuming
\(\alpha \in \{1/|\mathcal{O}|, 2/|\mathcal{O}|, \ldots, 1\}\) (since
\(\mathcal{O}\) is finite and \(T(\pi \mathbf{y})\) distribution is a
step function). For other \(\alpha\) values, tests are slightly
conservative (or require randomized tests, not discussed here).

Additional properties: - \textbf{Unbiased}:
\(P(\text{p-value} \leq \alpha | H_1) > \alpha\) - \textbf{Consistent}:
\(P(\text{p-value} \leq \alpha | H_1) \to 1\) as \(n \to \infty\) -
Converges to parametric counterpart when it exists

\subsubsection{Estimated p-values}\label{estimated-p-values}

In practice, the p-value is often \emph{estimated} using random
permutations when it is computationally infeasible to compute the exact
permutation p-value based on the entire permutation group.

Random permutations are typically drawn uniformly from the orbit
\(\mathcal{O}\) without replacement. In this Section, \(p\) denotes the
exact p-value computed from the entire orbit \(\mathcal{O}\), and
\(\hat{p}\) denotes its estimate computed from \(B\) randomly sampled
permutations.

If we force the first element to be the observed test statistic
\(T(Y)\), then \(T(Y)\) becomes over-represented in the sample of \(B\)
elements from \(\mathcal{O}\). Consequently, \(E(\hat{p}) > p\),
although \(\lim_{B \to \infty} \hat{p} = p\).

An unbiased estimator of \(p\), denoted \(\hat{p}_0\), can be obtained
by removing the constraint that \(T(Y)\) must be included in the sample
(i.e., by sampling permutations without including the observed statistic
by default). This ensures \(E(\hat{p}_0) = p\). However, as Phipson and
Smyth (2010) thoroughly explain, using this unbiased estimator can be
problematic because \(\hat{p}_0\) is almost never stochastically larger
than a uniform distribution on \([0,1]\) under \(H_0\). This is evident
from the fact that \(\hat{p}_0\) typically has a positive probability of
being exactly zero.

In any case, when computationally feasible, computing exact p-values is
always preferable to estimating them.

\subsection{Comparison with Parametric Linear
Models}\label{comparison-with-parametric-linear-models}

The histogram of test statistics from permuted data is well approximated
by a \textbf{Gaussian} curve.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(beta.perm, }\DecValTok{50}\NormalTok{, }\AttributeTok{probability =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{col =} \DecValTok{2}\NormalTok{)}
\FunctionTok{curve}\NormalTok{(}\FunctionTok{dnorm}\NormalTok{(x, }\FunctionTok{mean}\NormalTok{(beta.perm), }\FunctionTok{sd}\NormalTok{(beta.perm)), }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{col =} \DecValTok{1}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{3}\NormalTok{)}
\FunctionTok{points}\NormalTok{(beta1, }\DecValTok{0}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{3}\NormalTok{, }\AttributeTok{col =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-18-1} \end{center}

\subsubsection{Simple Linear Parametric
Model}\label{simple-linear-parametric-model}

Assume observed values distribute around true values
\(\beta_0 + \beta_1 X\) according to a Gaussian distribution:

\(Y = \text{linear part} + \text{normal error}\)

\(Y = \beta_0 + \beta_1 X + \varepsilon\)

\textbf{Linear model assumptions}: -
\(y_i = \beta_0 + \beta_1 x_i + \varepsilon_i\) (true linear
relationship plus error) - \(\varepsilon_i \sim N(0, \sigma^2)\) for all
\(i = 1, \ldots, n\) (normal errors with zero mean and constant
variance/homoscedasticity)

\subsubsection{Hypothesis Testing}\label{hypothesis-testing}

If assumptions hold:

\(\hat{\beta}_1 \sim N(\beta_1, \sigma^2 / \sum (x_i - \bar{x})^2)\)

Test statistic:

\(t = \frac{\hat{\beta}_1}{\text{std.dev}(\hat{\beta}_1)} = \frac{\hat{\beta}_1}{\sqrt{\frac{\sum_{i=1}^n (y_i - \hat{y}_i)^2}{\sum (x_i - \bar{x})^2} / (n-2)}}\)

If \(H_0: \beta_1 = 0\) is true, \(t \sim t(n-2)\).

For \texttt{reaction} data with \(H_1: \beta_1 \neq 0\) (two-sided):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{data =}\NormalTok{ reaction)}
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Reaction.Time ~ Age, data = reaction)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -6.535 -3.364 -0.272  2.676  7.839 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)  
## (Intercept) 10.30135    4.04407   2.547   0.0343 *
## Age          0.20647    0.07841   2.633   0.0300 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.678 on 8 degrees of freedom
## Multiple R-squared:  0.4643, Adjusted R-squared:  0.3973 
## F-statistic: 6.934 on 1 and 8 DF,  p-value: 0.03003
\end{verbatim}

Similar result, but with many more assumptions!

\subsubsection{Permutation Test
Assumptions}\label{permutation-test-assumptions}

What model do permutation tests assume?

Under \(H_0\): \(f(y) = f(y|x) \ \forall x\)

Under \(H_1\): No assumptions. For power, we hope:
\(H_1: E(y|x) = \beta_0 + \beta_1 x\) with \(\beta_1 \neq 0\) for some
\(x\)\\
i.e., \(H_1: E(yx) \neq E(x)E(y)\)

No other assumptions about \(f(y|x)\) distribution (normality, finite
moments, etc.).

\subsection{Permutationally Equivalent
Tests}\label{permutationally-equivalent-tests}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{(res\_cor }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{statTest =} \StringTok{"cor"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##               Test   Stat tail p-value
## Reaction.Time  cor 0.6814   ><  0.0410
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{(res\_t }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{statTest =} \StringTok{"t"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##               Test  Stat tail p-value
## Reaction.Time    t 2.633   ><  0.0410
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(res\_cor}\SpecialCharTok{@}\NormalTok{permT, res\_t}\SpecialCharTok{@}\NormalTok{permT, }\AttributeTok{pch =} \DecValTok{20}\NormalTok{, }\AttributeTok{col =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-20-1} \end{center}

\subsubsection{Conclusion}\label{conclusion}

\textbf{Permutation tests}: - Different from bootstrap methods
(permutation: without replacement; bootstrap: with replacement).
Permutation tests have optimal properties and (usually) exact Type I
error control. - General approach applicable in many contexts with
minimal assumptions. - Dedicated R packages:\\
* \texttt{coin}
\url{http://cran.r-project.org/web/packages/coin/index.html}\\
* \texttt{permuco}
\url{https://cran.r-project.org/web/packages/permuco/index.html}\\
* \texttt{flip}
\url{http://cran.r-project.org/web/packages/flip/index.html}
(development: \url{https://github.com/livioivil/flip})\\
* \texttt{flipscores}
\url{http://cran.r-project.org/web/packages/flipscores/index.html}
(development: \url{https://github.com/livioivil/flipscores})\\
* \texttt{multcomp}
\url{https://cran.r-project.org/web/packages/multcomp/index.html}\\
* \texttt{GFD}
\url{https://cran.r-project.org/web/packages/GFD/index.html}

\section{Special Cases}\label{special-cases}

\subsection{Rank Correlation}\label{rank-correlation}

\begin{itemize}
\tightlist
\item
  \(n\) observations of \(y\), interest in \(F(y|x)\)

  \begin{itemize}
  \tightlist
  \item
    Don't need \(y_1\) and \(y_2\) to be continuous or have finite
    moments
  \end{itemize}
\item
  Hypotheses:

  \begin{itemize}
  \tightlist
  \item
    \(H_0: F(y|x) = F(y|x') \ \forall x, x'\)\\
  \item
    \(H_1: \exists x < x' : F(y|x) < F(y|x')\) or directional
    alternatives\\
  \item
    Test statistic: rank correlation
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  (res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{, }\AttributeTok{statTest =} \StringTok{"rank"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                   Test  Stat tail p-value
## Reaction.Time Wilcoxon 2.189   ><  0.0204
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \CommentTok{\# Alternative using rank transformation:}
\NormalTok{  (res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(}\FunctionTok{rank}\NormalTok{(reaction}\SpecialCharTok{$}\NormalTok{Reaction.Time) }\SpecialCharTok{\textasciitilde{}} \FunctionTok{rank}\NormalTok{(reaction}\SpecialCharTok{$}\NormalTok{Age), }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{, }\AttributeTok{statTest =} \StringTok{"cor"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                              Test   Stat tail p-value
## rank.reaction.Reaction.Time.  cor 0.7153   ><  0.0222
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  (}\FunctionTok{cor.test}\NormalTok{(reaction}\SpecialCharTok{$}\NormalTok{Reaction.Time, reaction}\SpecialCharTok{$}\NormalTok{Age, }\AttributeTok{method =} \StringTok{"spearman"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in cor.test.default(reaction$Reaction.Time, reaction$Age, method =
## "spearman"): Impossibile calcolare p-value esatti in presenza di ties
\end{verbatim}

\begin{verbatim}
## 
##  Spearman's rank correlation rho
## 
## data:  reaction$Reaction.Time and reaction$Age
## S = 46.983, p-value = 0.02005
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##      rho 
## 0.715256
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{plot}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-22-1} \end{center}

\subsection{Two Independent Samples
Problem}\label{two-independent-samples-problem}

\begin{itemize}
\tightlist
\item
  Two samples: \(n_1\) observations from \(y_1\), \(n_2\) from \(y_2\)

  \begin{itemize}
  \tightlist
  \item
    No continuity or finite moment requirements
  \end{itemize}
\item
  Hypotheses:

  \begin{itemize}
  \tightlist
  \item
    \(H_0: F(y_1) = F(y_2)\)\\
  \item
    \(H_1: F(y_1) \neq F(y_2)\) (or directional)
  \end{itemize}
\item
  Test statistics:

  \begin{itemize}
  \tightlist
  \item
    Standardized mean difference (t-statistic)
  \end{itemize}
\item
  Estimated slope coefficient (group labels as dummy predictor)
\item
  Other permutationally equivalent statistics
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{data}\NormalTok{(}\StringTok{"seeds"}\NormalTok{)}
\NormalTok{  seeds }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(seeds)}
\NormalTok{  (res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ grp, }\AttributeTok{data =}\NormalTok{ seeds, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Test  Stat tail p-value
## y    t 2.061   ><  0.0526
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ grp, }\AttributeTok{data =}\NormalTok{ seeds))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ grp, data = seeds)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.331 -2.931 -1.651  4.663  7.863 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   10.147      1.242   8.168    9e-09 ***
## grp            3.345      1.623   2.061    0.049 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.303 on 27 degrees of freedom
## Multiple R-squared:  0.136,  Adjusted R-squared:  0.104 
## F-statistic: 4.249 on 1 and 27 DF,  p-value: 0.04903
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{plot}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-24-1} \end{center}

\subsubsection{Rank Test}\label{rank-test}

Can use rank-based statistics? Yes---equivalent to rank tests but with
exact distribution (no tie limitations).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  (res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ grp, }\AttributeTok{data =}\NormalTok{ seeds, }\AttributeTok{statTest =} \StringTok{"rank"}\NormalTok{, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##       Test  Stat tail p-value
## y Wilcoxon 2.148   ><  0.0292
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{wilcox.test}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ grp, }\AttributeTok{data =}\NormalTok{ seeds)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): non è
## possibile calcolare p-value esatto in presenza di ties
\end{verbatim}

\begin{verbatim}
## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  y by grp
## W = 53.5, p-value = 0.03353
## alternative hypothesis: true location shift is not equal to 0
\end{verbatim}

\subsection{Chi-square and Other Categorical
Methods}\label{chi-square-and-other-categorical-methods}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{data}\NormalTok{(}\StringTok{"seeds"}\NormalTok{)}
\NormalTok{  seeds}\SpecialCharTok{$}\NormalTok{Germinated }\OtherTok{\textless{}{-}} \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(seeds}\SpecialCharTok{$}\NormalTok{x)}
\NormalTok{  seeds}\SpecialCharTok{$}\NormalTok{Germinated }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(seeds}\SpecialCharTok{$}\NormalTok{Germinated)}
\NormalTok{  seeds}\SpecialCharTok{$}\NormalTok{grp }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(seeds}\SpecialCharTok{$}\NormalTok{grp)}
  \FunctionTok{table}\NormalTok{(seeds}\SpecialCharTok{$}\NormalTok{grp, seeds}\SpecialCharTok{$}\NormalTok{Germinated)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##     FALSE TRUE
##   0     8   12
##   1     3   17
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{chisq.test}\NormalTok{(seeds}\SpecialCharTok{$}\NormalTok{grp, seeds}\SpecialCharTok{$}\NormalTok{Germinated)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test with Yates' continuity correction
## 
## data:  seeds$grp and seeds$Germinated
## X-squared = 2.0063, df = 1, p-value = 0.1567
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  (res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Germinated }\SpecialCharTok{\textasciitilde{}}\NormalTok{ grp, }\AttributeTok{data =}\NormalTok{ seeds, }\AttributeTok{statTest =} \StringTok{"Chisq"}\NormalTok{, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                         Test  Stat tail p-value
## grp_|_Germinated Chi Squared 3.135    >  0.1610
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{plot}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-28-1} \end{center}

\ldots and Fisher's exact test:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fisher.test}\NormalTok{(seeds}\SpecialCharTok{$}\NormalTok{grp, seeds}\SpecialCharTok{$}\NormalTok{Germinated)}\SpecialCharTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1551874
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{flip}\NormalTok{(Germinated }\SpecialCharTok{\textasciitilde{}}\NormalTok{ grp, }\AttributeTok{data =}\NormalTok{ seeds, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                 Test   Stat tail p-value
## GerminatedFALSE    t -1.798   ><  0.1596
## GerminatedTRUE     t  1.798   ><  0.1596
\end{verbatim}

\subsection{ANOVA (C-sample)}\label{anova-c-sample}

Example: 3 \texttt{Age} groups: young \([18-35)\), middle \([35-60)\),
old \([60-100)\)

\begin{itemize}
\tightlist
\item
  C samples: \(n_i\) observations from \(y_i\) (\(i=1,\ldots,C\))

  \begin{itemize}
  \tightlist
  \item
    No continuity or finite moment requirements
  \end{itemize}
\item
  Hypotheses:

  \begin{itemize}
  \tightlist
  \item
    \(H_0: F(y_i) = F(y_j) \ \forall (i,j)\)\\
  \item
    \(H_1: \exists (i,j): F(y_i) \neq F(y_j)\)
  \end{itemize}
\item
  Test statistics:

  \begin{itemize}
  \tightlist
  \item
    F-statistic
  \item
    \(R^2\)
  \item
    Other permutationally equivalent statistics
  \item
    Rank-based alternatives
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reaction}\SpecialCharTok{$}\NormalTok{AgeCateg }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(reaction}\SpecialCharTok{$}\NormalTok{Age, }\FunctionTok{c}\NormalTok{(}\DecValTok{18}\NormalTok{, }\DecValTok{35}\NormalTok{, }\DecValTok{65}\NormalTok{, }\DecValTok{100}\NormalTok{), }\AttributeTok{right =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{(res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ AgeCateg, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{, }\AttributeTok{statTest =} \StringTok{"ANOVA"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##               Test Stat tail p-value
## Reaction.Time    F 4.02    >  0.0780
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ AgeCateg, }\AttributeTok{data =}\NormalTok{ reaction))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Reaction.Time ~ AgeCateg, data = reaction)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -6.495 -3.279  0.465  2.246  6.112 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(>|t|)    
## (Intercept)        16.157      2.331   6.932 0.000225 ***
## AgeCateg[35,65)     4.428      3.296   1.343 0.221144    
## AgeCateg[65,100)   11.418      4.037   2.828 0.025478 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.662 on 7 degrees of freedom
## Multiple R-squared:  0.5346, Adjusted R-squared:  0.4016 
## F-statistic:  4.02 on 2 and 7 DF,  p-value: 0.06878
\end{verbatim}

\subsubsection{Stochastic Ordering}\label{stochastic-ordering}

\begin{itemize}
\tightlist
\item
  Same assumptions as ANOVA
\item
  Hypotheses:

  \begin{itemize}
  \tightlist
  \item
    Same \(H_0: F(y_i) = F(y_j) \ \forall (i,j)\)
  \item
    But \(H_1: \exists (i,j): F(y_i) < F(y_j)\) (or \(>\))
  \end{itemize}
\end{itemize}

(More details on NPC later)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ AgeCateg, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{, }\AttributeTok{tail =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                                    Test   Stat tail p-value
## Reaction.Time_|_AgeCateg.[35,65).     t 0.1423    >  0.4336
## Reaction.Time_|_AgeCateg.[65,100).    t 2.2444    >  0.0220
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{npc}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    comb.funct nVar  Stat p-value
## V1     Fisher    2 4.652  0.0202
\end{verbatim}

\subsection{Stratified Permutations (Discrete
Nuisances)}\label{stratified-permutations-discrete-nuisances}

Test \(X=\) \texttt{Age} with \(Z =\) \texttt{Gender} as nuisance in
\texttt{reaction} data.

Under \(H_0\): \(f(y|x,z) = f(y|x',z) = f(y|z) \ \forall (x,x')\)

Thus, under \(H_0\), \(f(y_i) = f(y_j)\) only if \(z_i = z_j\) (same
gender).

Can we permute as before? NO. Permute only within strata defined by
\(Z\).

\textbf{Remark}: - No linear nuisance effect assumption - Allow
heteroscedastic errors across strata

Test statistic remains unchanged.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age, }\AttributeTok{Strata =} \SpecialCharTok{\textasciitilde{}}\NormalTok{Gender, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##               Test  Stat tail p-value
## Reaction.Time    t 2.633   ><  0.0718
\end{verbatim}

Alternative model (more on NPC later):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(Reaction.Time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age}\SpecialCharTok{*}\NormalTok{Gender, }\AttributeTok{Strata =} \SpecialCharTok{\textasciitilde{}}\NormalTok{Gender, }\AttributeTok{data =}\NormalTok{ reaction, }\AttributeTok{perms =} \DecValTok{5000}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                               Test    Stat tail p-value
## Reaction.Time_|_Age              t  2.4826   ><  0.0750
## Reaction.Time_|_Age:Gender.M.    t -0.6518   ><  0.3394
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{npc}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    comb.funct nVar  Stat p-value
## V1     Fisher    2 3.671  0.1406
\end{verbatim}

\section{Paired samples}\label{paired-samples}

Understanding the Model: \(Y=\gamma_0+\gamma_1 Z+\beta X+\varepsilon\)

Consider the model: - \(Z\) represents Subject ID (\(i=1,\ldots,n\)) -
\(X\) indicates pre/post-treatment status (typically coded as 0 for
pre-treatment, 1 for post-treatment) - Each subject in \(Z\) has one
pre-treatment and one post-treatment observation

The null hypothesis to test is \(H_0: \beta=0\).

When permutations are constrained within levels of \(Z\) (within each
subject), this becomes equivalent to flipping the sign of the difference
between post- and pre-treatment measurements.

Let \(D\) be the vector of these differences with \(n\) observations.
The null hypothesis can be rewritten as \(H_0: E(D)=0\).

\subsection{Advantages of this
approach}\label{advantages-of-this-approach}

One major advantage is that we don't need to estimate the Fisher
Information (i.e., the residual variance). Let's demonstrate this with a
paired t-test example:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{20}
\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n)}

\CommentTok{\# Generate sign flips for permutation testing}
\NormalTok{FLIPS }\OtherTok{\textless{}{-}}\NormalTok{ flipscores}\SpecialCharTok{:::}\FunctionTok{.make\_flips}\NormalTok{(n, }\DecValTok{1000}\NormalTok{)}
\FunctionTok{head}\NormalTok{(FLIPS)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
## [1,]    1    1    1    1    1    1    1    1    1     1     1     1     1     1
## [2,]   -1    1   -1   -1    1    1   -1    1   -1     1     1     1    -1     1
## [3,]   -1   -1    1    1    1   -1   -1    1   -1     1    -1    -1     1     1
## [4,]    1   -1   -1    1    1    1    1   -1   -1     1     1    -1    -1     1
## [5,]    1   -1    1   -1   -1    1   -1   -1    1     1    -1     1    -1    -1
## [6,]    1    1    1   -1    1   -1   -1   -1   -1     1     1    -1     1    -1
##      [,15] [,16] [,17] [,18] [,19] [,20]
## [1,]     1     1     1     1     1     1
## [2,]    -1    -1     1    -1    -1    -1
## [3,]    -1     1     1     1    -1     1
## [4,]    -1     1     1     1     1     1
## [5,]     1     1    -1     1     1     1
## [6,]    -1     1     1    -1    -1    -1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate test statistics for each permutation}
\NormalTok{Tstat }\OtherTok{\textless{}{-}}\NormalTok{ FLIPS }\SpecialCharTok{\%*\%}\NormalTok{ y}
\NormalTok{flipscores}\SpecialCharTok{:::}\FunctionTok{.t2p}\NormalTok{(Tstat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.124
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Monte Carlo simulation to check Type I error rate}
\NormalTok{MCMC }\OtherTok{\textless{}{-}} \DecValTok{10000}
\NormalTok{Y }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{rnorm}\NormalTok{(n }\SpecialCharTok{*}\NormalTok{ MCMC), n, MCMC)}
\NormalTok{Tstat }\OtherTok{\textless{}{-}}\NormalTok{ FLIPS }\SpecialCharTok{\%*\%}\NormalTok{ Y}
\NormalTok{p.values }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(Tstat, }\DecValTok{2}\NormalTok{, flipscores}\SpecialCharTok{:::}\NormalTok{.t2p)}
\FunctionTok{mean}\NormalTok{(p.values }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.047
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lightweight t{-}test function}
\NormalTok{t.test.light }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(Y, }\AttributeTok{tail =} \DecValTok{1}\NormalTok{) \{}
\NormalTok{  sd }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(Y, }\DecValTok{2}\NormalTok{, sd, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(Y)}
\NormalTok{  ts }\OtherTok{\textless{}{-}} \FunctionTok{colMeans}\NormalTok{(Y, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ sd }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(n)}
  \FunctionTok{pt}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{ts, }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}
\NormalTok{\}}

\CommentTok{\# Test with heteroscedastic data}
\NormalTok{Y }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(MCMC, }\FunctionTok{rnorm}\NormalTok{(n, }\AttributeTok{sd =} \FunctionTok{exp}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n)))}
\NormalTok{Tstat }\OtherTok{\textless{}{-}}\NormalTok{ FLIPS }\SpecialCharTok{\%*\%}\NormalTok{ Y}
\NormalTok{p.values }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(Tstat, }\DecValTok{2}\NormalTok{, flipscores}\SpecialCharTok{:::}\NormalTok{.t2p)}
\NormalTok{p.values\_param }\OtherTok{\textless{}{-}} \FunctionTok{t.test.light}\NormalTok{(Y)}

\CommentTok{\# Compare Type I error rates}
\FunctionTok{mean}\NormalTok{(p.values }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0438
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(p.values\_param }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0095
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize p{-}value distributions}
\FunctionTok{plot.ecdf}\NormalTok{(p.values,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}\AttributeTok{asp=}\DecValTok{1}\NormalTok{)}
\FunctionTok{plot.ecdf}\NormalTok{(p.values\_param,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{col =} \DecValTok{3}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{col =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-34-1} \end{center}

In this example, we compare a permutation-based approach (sign-flipping
test) with a parametric t-test:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Permutation Test}: We generate sign flips that correspond to
  within-subject permutations. The test statistic is calculated for each
  sign-flipped version of the data, creating a null distribution against
  which we compare our observed statistic.
\item
  \textbf{Parametric t-test}: We use a standard t-test that assumes
  normality and constant variance.
\item
  \textbf{Heteroscedasticity Simulation}: The second part of the code
  generates data with increasing variance across observations
  (\texttt{sd\ =\ exp(1:n)}). This violates the constant variance
  assumption of the parametric t-test.
\end{enumerate}

The empirical cumulative distribution function (ECDF) plot shows how the
p-values from both methods compare. Under the null hypothesis with
correct assumptions, both should produce uniformly distributed p-values
(follow the diagonal line). When assumptions are violated, the
parametric test may produce inflated Type I error rates, while the
permutation test maintains correct error control due to its
distribution-free nature.

\textbf{Key Insights}: - The permutation test doesn't require estimating
residual variance - It remains valid even when parametric assumptions
(like homoscedasticity) are violated - The method is particularly
powerful for paired data where within-subject comparisons are natural -
Sign-flipping is equivalent to permuting within subjects when testing
for treatment effects in paired designs

\subsection{Repeated measures and mixed
models}\label{repeated-measures-and-mixed-models}

More properly this approach is known as Random coefficient Analysis /
Group-level analysis

\begin{itemize}
\item
  Basso \& Finos (2012). Exact Multivariate Permutation Tests for Fixed
  Effects in Mixed-Models. \emph{Communications in Statistics - Theory
  and Methods}, 41: 2991 - 3001.
\item
  Finos \& Basso (2014) Permutation tests for between-unit fixed effects
  in multivariate generalized linear mixed models. \emph{Stat Comput}
  24, 941--952.
\end{itemize}

A more complete approach:

\begin{itemize}
\tightlist
\item
  Andreella, Goeman, Hemerik, Finos (2025) Robust Inference for
  Generalized Linear Mixed Models: A ``Two-Stage Summary Statistics''
  Approach Based on Score Sign Flipping. Psychometrika, 1-23.
\end{itemize}

\section{Multivariate Testing}\label{multivariate-testing}

\subsection{Seeds Data}\label{seeds-data}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# install.packages("flip")}
\FunctionTok{library}\NormalTok{(flip)}
\end{Highlighting}
\end{Shaded}

Remove \texttt{NA}s:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(seeds, }\AttributeTok{package =} \StringTok{"flip"}\NormalTok{)}
\NormalTok{seeds }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(seeds)}
\NormalTok{seeds}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    grp    x     y
## 9    0 6.03 12.54
## 10   0 4.20 14.81
## 11   0 4.49 16.71
## 12   0 2.00  7.53
## 13   0 2.84  7.02
## 14   0 3.88  8.09
## 15   0 2.04  5.76
## 16   0 5.48 18.01
## 17   0 2.31  8.81
## 18   0 1.90  8.17
## 19   0 1.75  6.62
## 20   0 3.02  7.69
## 24   1 3.31 18.49
## 25   1 6.56 19.20
## 26   1 3.16  9.85
## 27   1 4.07 15.83
## 28   1 2.09  6.16
## 29   1 6.72 17.58
## 30   1 3.93 19.29
## 31   1 2.56 10.77
## 32   1 8.30 18.31
## 33   1 4.21 10.56
## 34   1 1.86  9.48
## 35   1 3.09 12.54
## 36   1 5.09 18.35
## 37   1 4.08 11.84
## 38   1 3.63 11.44
## 39   1 2.61  7.66
## 40   1 5.21 12.00
\end{verbatim}

\subsection{Marginal vs Joint
Distribution}\label{marginal-vs-joint-distribution}

Use permutation methods to test for group differences (\texttt{grp}) on
both \texttt{x} and \texttt{y}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(flip)}
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(. }\SpecialCharTok{\textasciitilde{}}\NormalTok{ grp, }\AttributeTok{data =}\NormalTok{ seeds, }\AttributeTok{flipReturn =} \FunctionTok{list}\NormalTok{(}\AttributeTok{permP =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{permT =} \ConstantTok{TRUE}\NormalTok{))}
\FunctionTok{hist}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-37-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# flipReturn = list(permP = TRUE, permT = TRUE) not strictly needed; useful later}
\end{Highlighting}
\end{Shaded}

We can test the two variables separately but lack an overall p-value (is
there ANY difference?).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-38-1} \end{center}

Next we'll see: - How to combine p-values (e.g., Fisher's combining
function) for global hypothesis testing - How to use closed testing
procedures to adjust p-values: which variables differ?

\subsection{Rejection Regions (and Overall
Testing)}\label{rejection-regions-and-overall-testing}

In univariate settings, defining `far from null' (usually from test
statistic = 0) is straightforward. In multivariate settings, there are
multiple (no uniformly best) approaches.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# install.packages("plotrix")}
\FunctionTok{library}\NormalTok{(}\StringTok{"plotrix"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: il pacchetto 'plotrix' è stato creato con R versione 4.5.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res.sumt2 }\OtherTok{\textless{}{-}} \FunctionTok{npc}\NormalTok{(res, }\StringTok{"sumT2"}\NormalTok{, }\AttributeTok{flipReturn =} \FunctionTok{list}\NormalTok{(}\AttributeTok{permP =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{permT =} \ConstantTok{TRUE}\NormalTok{))}
\NormalTok{limsumt2 }\OtherTok{\textless{}{-}}\NormalTok{ res.sumt2}\SpecialCharTok{@}\NormalTok{permT[}\FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(res.sumt2}\SpecialCharTok{@}\NormalTok{permP }\SpecialCharTok{{-}} \FloatTok{0.05}\NormalTok{))]}
\NormalTok{res.sumt }\OtherTok{\textless{}{-}} \FunctionTok{npc}\NormalTok{(res, }\StringTok{"sumT"}\NormalTok{, }\AttributeTok{flipReturn =} \FunctionTok{list}\NormalTok{(}\AttributeTok{permP =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{permT =} \ConstantTok{TRUE}\NormalTok{))}
\NormalTok{limsumt }\OtherTok{\textless{}{-}}\NormalTok{ res.sumt}\SpecialCharTok{@}\NormalTok{permT[}\FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(res.sumt}\SpecialCharTok{@}\NormalTok{permP }\SpecialCharTok{{-}} \FloatTok{0.05}\NormalTok{))]}
\NormalTok{res.maxt }\OtherTok{\textless{}{-}} \FunctionTok{npc}\NormalTok{(res, }\StringTok{"maxT"}\NormalTok{, }\AttributeTok{flipReturn =} \FunctionTok{list}\NormalTok{(}\AttributeTok{permP =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{permT =} \ConstantTok{TRUE}\NormalTok{))}
\NormalTok{limmaxt }\OtherTok{\textless{}{-}}\NormalTok{ res.maxt}\SpecialCharTok{@}\NormalTok{permT[}\FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(res.maxt}\SpecialCharTok{@}\NormalTok{permP }\SpecialCharTok{{-}} \FloatTok{0.05}\NormalTok{))]}

\FunctionTok{plot}\NormalTok{(res}\SpecialCharTok{@}\NormalTok{permT[,}\DecValTok{1}\NormalTok{], res}\SpecialCharTok{@}\NormalTok{permT[,}\DecValTok{2}\NormalTok{], }\AttributeTok{col =} \StringTok{"\#F2AD00"}\NormalTok{, }\AttributeTok{bg =} \StringTok{"\#F98400"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{21}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Some Rejection Regions (alpha = .05)"}\NormalTok{, }\AttributeTok{asp =} \DecValTok{1}\NormalTok{)}
\FunctionTok{draw.circle}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, limsumt2}\SpecialCharTok{\^{}}\NormalTok{.}\DecValTok{5}\NormalTok{, }\AttributeTok{border =} \StringTok{"red"}\NormalTok{)}
\FunctionTok{segments}\NormalTok{(}\FunctionTok{c}\NormalTok{(limsumt, }\SpecialCharTok{{-}}\NormalTok{limsumt, limsumt, }\SpecialCharTok{{-}}\NormalTok{limsumt), }\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{),}
         \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{), }\FunctionTok{c}\NormalTok{(limsumt, }\SpecialCharTok{{-}}\NormalTok{limsumt, }\SpecialCharTok{{-}}\NormalTok{limsumt, limsumt), }\AttributeTok{col =} \StringTok{"green"}\NormalTok{)}
\FunctionTok{segments}\NormalTok{(}\FunctionTok{c}\NormalTok{(limmaxt, }\SpecialCharTok{{-}}\NormalTok{limmaxt, }\SpecialCharTok{{-}}\NormalTok{limmaxt, limmaxt), }\FunctionTok{c}\NormalTok{(limmaxt, limmaxt, }\SpecialCharTok{{-}}\NormalTok{limmaxt, }\SpecialCharTok{{-}}\NormalTok{limmaxt),}
         \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{limmaxt, }\SpecialCharTok{{-}}\NormalTok{limmaxt, limmaxt, limmaxt), }\FunctionTok{c}\NormalTok{(limmaxt, }\SpecialCharTok{{-}}\NormalTok{limmaxt, }\SpecialCharTok{{-}}\NormalTok{limmaxt, limmaxt), }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{)}
\FunctionTok{legend}\NormalTok{(}\StringTok{"topright"}\NormalTok{, }\AttributeTok{legend =} \FunctionTok{c}\NormalTok{(}\StringTok{"SumT\^{}2"}\NormalTok{, }\StringTok{"Sum |T|"}\NormalTok{, }\StringTok{"maxT"}\NormalTok{),}
       \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{, }\StringTok{"blue"}\NormalTok{), }\AttributeTok{bty =} \StringTok{"n"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-39-1} \end{center}

\textbf{REMARK}: We can derive the p-value distribution by computing
p-values for each test statistic (observed and permuted data). This
yields the multivariate p-value distribution:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(res}\SpecialCharTok{@}\NormalTok{permP, }\AttributeTok{col =} \StringTok{"\#F2AD00"}\NormalTok{, }\AttributeTok{bg =} \StringTok{"\#F98400"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{21}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Joint Distribution of P{-}values"}\NormalTok{, }\AttributeTok{asp =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-40-1} \end{center}

\subsubsection{Fisher Combining
Function}\label{fisher-combining-function}

Examine rejection regions for univariate tests and Fisher combination.
Intersection of each univariate test with Fisher region defines closed
testing rejection region (adjusted for multiple testing).

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-41-1} \end{center}

\subsubsection{Tippett (min-p) Combining
Function}\label{tippett-min-p-combining-function}

Examine rejection regions for univariate tests and Tippett combination.
Intersection defines closed testing rejection region. This coincides
with Westfall \& Young shortcut.

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-42-1} \end{center}

\section{FWER Control via Permutation
Tests}\label{fwer-control-via-permutation-tests}

\subsection{Permutation Bonferroni}\label{permutation-bonferroni}

Bonferroni is conservative:

\begin{itemize}
\tightlist
\item
  \textbf{Bonferroni bound}: Reject if p-value \(\leq \alpha/m\)
\item
  \textbf{By Boole's inequality}: Guaranteed FWER \(\leq \alpha\), but
  often FWER \(< \alpha\)
\item
  \textbf{Can we improve?}: Reject if p-value
  \(\leq \tilde{\alpha} > \alpha/m\) while maintaining FWER control
\item
  \textbf{Yes}: Via permutations
\end{itemize}

\subsection{Improved Bonferroni}\label{improved-bonferroni}

\begin{itemize}
\item
  \textbf{Reduced \(\alpha\)}: Reject \(H_i\) if
  \(p_i \leq \tilde{\alpha}\)
\item
  \textbf{FWER control?}: \[
  \begin{aligned}
  \text{FWER} &= P(\text{$p_i \leq \tilde{\alpha}$ for at least one true $H_i$}) \\
  &= P\left( \bigcup_{i \in T} \{p_i \leq \tilde{\alpha}\} \right) \\
  &= P\left( \min_{i \in T} p_i \leq \tilde{\alpha} \right) \leq \alpha
  \end{aligned}
   \]
\item
  \textbf{How to determine \(\tilde{\alpha}\)?}: Use permutations to
  find minimum p-value distribution
\end{itemize}

\subsection{Multiple Testing via
Permutations}\label{multiple-testing-via-permutations}

\textbf{Single-step min-P method}:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calculate smallest p-value \(m\) for real data\\
\item
  Randomly permute data\\
\item
  Calculate new p-values for all tests on permuted data\\
\item
  Calculate smallest p-value \(m^\pi\) for permuted data\\
\item
  Repeat permutations many times (e.g., k = 1000):
  \(m^\pi_1, \ldots, m^\pi_k\)\\
\item
  Calculate \(\tilde{\alpha}\) as \(\alpha\)-quantile of
  \(m^\pi_1, \ldots, m^\pi_k\)
\end{enumerate}

\textbf{Multiple testing result}: Reject all hypotheses with
(non-permuted) p-values \(\leq \tilde{\alpha}\)

\subsection{P-value Correlation
Structure}\label{p-value-correlation-structure}

\textbf{Permutation}:

\begin{itemize}
\tightlist
\item
  Destroys covariate-response correlation\\
\item
  Preserves covariate correlations
\end{itemize}

\textbf{Consequence}:

\begin{itemize}
\tightlist
\item
  P-values of correlated tests remain correlated in permutations\\
\item
  Minimum p-value distribution correctly accounts for correlations
\end{itemize}

\textbf{When is improvement over Bonferroni large?}:

\begin{itemize}
\tightlist
\item
  Negatively correlated p-values: typically no gain\\
\item
  Independent p-values: minimal gain\\
\item
  Positively correlated p-values: potentially large gain
\end{itemize}

\subsection{Improved Holm: Westfall \&
Young}\label{improved-holm-westfall-young}

\emph{Westfall PH, Young SS (1993) Resampling-Based Multiple Testing:
Examples and Methods for p-Value Adjustment. Wiley} \textbf{Sequential
permutation multiple testing}:

\begin{itemize}
\item
  \textbf{Single-step}: Permutation equivalent of Bonferroni
\item
  \textbf{Holm equivalent}: Westfall \& Young method\\
  \textbf{min-P algorithm}:
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Start with all hypotheses 2. Repeat:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Perform single-step min-P to calculate \(\tilde{\alpha}\)
\item
  Reject hypotheses with p-value \(\leq \tilde{\alpha}\)
\item
  Remove rejected hypotheses\\
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Until no new rejections
\end{enumerate}

\subsection{General Framework: Closed
Testing}\label{general-framework-closed-testing}

\emph{Marcus R, Peritz E, Gabriel KR (1976). On closed testing
procedures with special reference to ordered analysis of variance.
Biometrika 63: 655-660.}

Test each node with any multivariate permutation test.

Westfall \& Young is a special case of closed testing (each node uses
min-p/Tippett or max-T combining function).

\subsubsection{Closure Set}\label{closure-set}

\begin{center}\includegraphics[width=9.82in]{./figs/closed_set} \end{center}

Adjusted \(\tilde{p}_A = \max(p_A, p_{AB}, p_{AC}, p_{ABC})\)

In our data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(res }\OtherTok{\textless{}{-}} \FunctionTok{flip.adjust}\NormalTok{(res, }\AttributeTok{method =} \StringTok{"Fisher"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Test  Stat tail p-value Adjust:Fisher
## x    t 1.320   ><  0.1710        0.1710
## y    t 2.061   ><  0.0350        0.0620
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(res }\OtherTok{\textless{}{-}} \FunctionTok{flip.adjust}\NormalTok{(res, }\AttributeTok{method =} \StringTok{"maxT"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Test  Stat tail p-value Adjust:Fisher Adjust:maxT
## x    t 1.320   ><  0.1710        0.1710      0.1710
## y    t 2.061   ><  0.0350        0.0620      0.0600
\end{verbatim}

Conclusion

\textbf{Accounting for dependencies}: Adjusted p-values become lower
(more rejections).

\textbf{When?}:

\begin{itemize}
\tightlist
\item
  Negative correlation: generally no gain\\
\item
  Independent p-values: little or no gain\\
\item
  Positive correlation: substantial gain (note: two-sided tests with
  negatively correlated test statistics yield positively correlated
  p-values)
\end{itemize}

\textbf{Real data}: Often correlated variables → permutations
advantageous

\textbf{How?}: \texttt{R:\ library(flip);\ flip();\ flip.adjust()}

\section{Case Study: Pharmacokinetic Study of
Carbidopa}\label{case-study-pharmacokinetic-study-of-carbidopa}

Description:\\
\url{http://webserv.jcu.edu/math//faculty/TShort/Bradstreet/part2/part2-table6.html}

12 healthy male subjects in three-period crossover design receiving
three graded doses (25, 50, 100 mg) of Carbidopa q8h. Seven-day washout
between periods. Pharmacokinetic variables AUC, Cmax, Tmax calculated
from plasma concentrations at 0, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 8 hours
postdosing after second dose on day 6.

Dataset:\\
\url{http://webserv.jcu.edu/math//faculty/TShort/Bradstreet/part2/Bradp2t6.txt}

Analyze without accounting for study periods (randomized within
subjects).

Research questions: 1. Is there a dose response for AUC, Cmax, or Tmax?
Overall? 2. Can dose proportionality be established? (Fit linear model
for each endpoint, discuss results)

\subsection{Solution}\label{solution}

Address both questions with single analysis: linear model (accounting
for individual variability) on log-transformed endpoints.

\begin{Shaded}
\begin{Highlighting}[]
 \CommentTok{\# Read and prepare data}
\NormalTok{ dati }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"http://webserv.jcu.edu/math//faculty/TShort/Bradstreet/part2/Bradp2t6.txt"}\NormalTok{,}
                  \AttributeTok{skip =} \DecValTok{1}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{ dati }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(dati[,}\DecValTok{1}\NormalTok{], }\FunctionTok{matrix}\NormalTok{(}\FunctionTok{as.matrix}\NormalTok{(dati[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{]), }\FunctionTok{nrow}\NormalTok{(dati)}\SpecialCharTok{*}\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{))}
 \FunctionTok{colnames}\NormalTok{(dati) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Sub"}\NormalTok{, }\StringTok{"Dose"}\NormalTok{, }\StringTok{"AUC"}\NormalTok{, }\StringTok{"Cmax"}\NormalTok{, }\StringTok{"Tmax"}\NormalTok{)}
\NormalTok{ dati }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(dati)}
 \FunctionTok{str}\NormalTok{(dati)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    36 obs. of  5 variables:
##  $ Sub : num  1 2 3 4 5 6 7 8 9 10 ...
##  $ Dose: num  100 25 50 50 50 25 100 25 50 25 ...
##  $ AUC : num  604 140 386 175 605 ...
##  $ Cmax: num  137 44.4 86.6 46.4 194 44.9 318 29 119 58.4 ...
##  $ Tmax: num  1.5 1 1.5 1.5 0.5 1 1 1 2 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
 \CommentTok{\# Log{-}transform responses (linear relationship indicates proportionality)}
\NormalTok{ dati[,}\DecValTok{3}\SpecialCharTok{:}\DecValTok{5}\NormalTok{] }\OtherTok{\textless{}{-}} \FunctionTok{log}\NormalTok{(dati[,}\DecValTok{3}\SpecialCharTok{:}\DecValTok{5}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
 \CommentTok{\# Descriptives and plots}
 \FunctionTok{summary}\NormalTok{(dati[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Dose             AUC             Cmax            Tmax        
##  Min.   : 25.00   Min.   :4.337   Min.   :3.219   Min.   :-0.6931  
##  1st Qu.: 25.00   1st Qu.:5.156   1st Qu.:3.966   1st Qu.: 0.0000  
##  Median : 50.00   Median :5.886   Median :4.485   Median : 0.2027  
##  Mean   : 58.33   Mean   :5.873   Mean   :4.547   Mean   : 0.2474  
##  3rd Qu.:100.00   3rd Qu.:6.539   3rd Qu.:5.280   3rd Qu.: 0.6931  
##  Max.   :100.00   Max.   :7.335   Max.   :5.989   Max.   : 1.0986
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
 \FunctionTok{by}\NormalTok{(dati[,}\DecValTok{3}\SpecialCharTok{:}\DecValTok{5}\NormalTok{], dati}\SpecialCharTok{$}\NormalTok{Dose, summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## dati$Dose: 25
##       AUC             Cmax            Tmax        
##  Min.   :4.337   Min.   :3.219   Min.   :-0.6931  
##  1st Qu.:4.803   1st Qu.:3.390   1st Qu.: 0.0000  
##  Median :4.972   Median :3.801   Median : 0.0000  
##  Mean   :5.051   Mean   :3.783   Mean   : 0.2071  
##  3rd Qu.:5.289   3rd Qu.:4.022   3rd Qu.: 0.6931  
##  Max.   :5.818   Max.   :4.464   Max.   : 0.6931  
## ------------------------------------------------------------ 
## dati$Dose: 50
##       AUC             Cmax            Tmax        
##  Min.   :5.133   Min.   :3.837   Min.   :-0.6931  
##  1st Qu.:5.670   1st Qu.:4.374   1st Qu.: 0.0000  
##  Median :5.886   Median :4.484   Median : 0.2027  
##  Mean   :5.815   Mean   :4.479   Mean   : 0.1689  
##  3rd Qu.:5.967   3rd Qu.:4.625   3rd Qu.: 0.4055  
##  Max.   :6.405   Max.   :5.268   Max.   : 1.0986  
## ------------------------------------------------------------ 
## dati$Dose: 100
##       AUC             Cmax            Tmax       
##  Min.   :6.164   Min.   :4.920   Min.   :0.0000  
##  1st Qu.:6.607   1st Qu.:5.229   1st Qu.:0.0000  
##  Median :6.782   Median :5.412   Median :0.4055  
##  Mean   :6.751   Mean   :5.378   Mean   :0.3662  
##  3rd Qu.:6.922   3rd Qu.:5.515   3rd Qu.:0.6931  
##  Max.   :7.335   Max.   :5.989   Max.   :1.0986
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
 \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
 \FunctionTok{plot}\NormalTok{(dati}\SpecialCharTok{$}\NormalTok{Dose, dati}\SpecialCharTok{$}\NormalTok{AUC, }\AttributeTok{ylab =} \StringTok{"log(AUC)"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Dose"}\NormalTok{, }\AttributeTok{main =} \StringTok{"Dose vs log(AUC)"}\NormalTok{)}
\NormalTok{ temp}\OtherTok{=}\FunctionTok{sapply}\NormalTok{(}\FunctionTok{unique}\NormalTok{(dati}\SpecialCharTok{$}\NormalTok{Sub), }\ControlFlowTok{function}\NormalTok{(s) \{}
\NormalTok{ d }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(dati, Sub }\SpecialCharTok{==}\NormalTok{ s)}
\NormalTok{ d }\OtherTok{\textless{}{-}}\NormalTok{ d[}\FunctionTok{order}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{Dose),]}
 \FunctionTok{lines}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{Dose, d}\SpecialCharTok{$}\NormalTok{AUC, }\AttributeTok{col =}\NormalTok{ s, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\NormalTok{ \})}
 
 \FunctionTok{plot}\NormalTok{(dati}\SpecialCharTok{$}\NormalTok{Dose, dati}\SpecialCharTok{$}\NormalTok{Cmax, }\AttributeTok{ylab =} \StringTok{"log(Cmax)"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Dose"}\NormalTok{, }\AttributeTok{main =} \StringTok{"Dose vs log(Cmax)"}\NormalTok{)}
\NormalTok{ temp}\OtherTok{=}\FunctionTok{sapply}\NormalTok{(}\FunctionTok{unique}\NormalTok{(dati}\SpecialCharTok{$}\NormalTok{Sub), }\ControlFlowTok{function}\NormalTok{(s) \{}
\NormalTok{ d }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(dati, Sub }\SpecialCharTok{==}\NormalTok{ s)}
\NormalTok{ d }\OtherTok{\textless{}{-}}\NormalTok{ d[}\FunctionTok{order}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{Dose),]}
 \FunctionTok{lines}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{Dose, d}\SpecialCharTok{$}\NormalTok{Cmax, }\AttributeTok{col =}\NormalTok{ s, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\NormalTok{\})}
 
 \FunctionTok{plot}\NormalTok{(dati}\SpecialCharTok{$}\NormalTok{Dose, dati}\SpecialCharTok{$}\NormalTok{Tmax, }\AttributeTok{ylab =} \StringTok{"log(Tmax)"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Dose"}\NormalTok{, }\AttributeTok{main =} \StringTok{"Dose vs log(Tmax)"}\NormalTok{)}
\NormalTok{ temp}\OtherTok{=}\FunctionTok{sapply}\NormalTok{(}\FunctionTok{unique}\NormalTok{(dati}\SpecialCharTok{$}\NormalTok{Sub), }\ControlFlowTok{function}\NormalTok{(s) \{}
\NormalTok{ d }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(dati, Sub }\SpecialCharTok{==}\NormalTok{ s)}
\NormalTok{ d }\OtherTok{\textless{}{-}}\NormalTok{ d[}\FunctionTok{order}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{Dose),]}
 \FunctionTok{lines}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{Dose, d}\SpecialCharTok{$}\NormalTok{Tmax, }\AttributeTok{col =}\NormalTok{ s, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\NormalTok{ \})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-46-1} \end{center}

Simple solution:

\begin{Shaded}
\begin{Highlighting}[]
 \FunctionTok{library}\NormalTok{(flip)}
\NormalTok{ res }\OtherTok{\textless{}{-}} \FunctionTok{flip}\NormalTok{(. }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Dose, }\AttributeTok{data =}\NormalTok{ dati, }\AttributeTok{Strata =} \SpecialCharTok{\textasciitilde{}}\NormalTok{Sub, }\AttributeTok{statTest =} \StringTok{"coeff"}\NormalTok{)}
 \FunctionTok{summary}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Call:
##  flip(Y = . ~ Dose, data = dati, statTest = "coeff", Strata = ~Sub) 
## 999 permutations.
## 
##       Test   Stat tail p-value sig.
## AUC  coeff 0.0221   ><  0.0010  ***
## Cmax coeff 0.0208   ><  0.0010  ***
## Tmax coeff 0.0024   ><  0.2950
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
 \CommentTok{\# statTest = "coeff": estimated linear model coefficient}
 \FunctionTok{hist}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{perm_files/figure-latex/unnamed-chunk-47-1} \end{center}

Multivariate: - Overall

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ res }\OtherTok{\textless{}{-}} \FunctionTok{flip.adjust}\NormalTok{(res)}
 \FunctionTok{npc}\NormalTok{(res, }\StringTok{"Fisher"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    comb.funct nVar  Stat p-value
## V1     Fisher    3 15.04  0.0010
\end{verbatim}

Dose effect exists overall.

\begin{itemize}
\tightlist
\item
  By endpoint (closed testing with max-t). Try different methods (e.g.,
  \texttt{method\ =\ "Fisher"}) and compare \texttt{method\ =\ "minP"}
  with \texttt{method\ =\ "Holm"}.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ res }\OtherTok{\textless{}{-}} \FunctionTok{flip.adjust}\NormalTok{(res, }\AttributeTok{method =} \StringTok{"holm"}\NormalTok{)}
\NormalTok{ res }\OtherTok{\textless{}{-}} \FunctionTok{flip.adjust}\NormalTok{(res, }\AttributeTok{method =} \StringTok{"Fisher"}\NormalTok{)}
 \FunctionTok{summary}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Call:
##  flip(Y = . ~ Dose, data = dati, statTest = "coeff", Strata = ~Sub) 
## 999 permutations.
## 
##       Test   Stat tail p-value Adjust:maxT Adjust:holm Adjust:Fisher sig.
## AUC  coeff 0.0221   ><  0.0010      0.0010      0.0030        0.0010  ***
## Cmax coeff 0.0208   ><  0.0010      0.0010      0.0030        0.0010  ***
## Tmax coeff 0.0024   ><  0.2950      0.2950      0.2950        0.2950
\end{verbatim}

\texttt{AUC} and \texttt{Cmax} show significant effects after
multiplicity correction; \texttt{Tmax} does not.

\section{Minimal Bibliography}\label{minimal-bibliography}

\textbf{Grounding Theory}:\\
- Pesarin (2001) \emph{Multivariate Permutation Tests: With Applications
in Biostatistics}. Wiley, New York

\textbf{Alternative permutation testing approach}:\\
- Hemerik J, Goeman J. Exact testing with random permutations. Test.
2018;27(4):811-825. \url{doi:10.1007/s11749-017-0571-1}

\textbf{Flexible GLM approach via sign-flip score test}:\\
- Hemerik, Goeman and Finos (2020) Robust testing in generalized linear
models by sign flipping score contributions. \emph{Journal of the Royal
Statistical Society Series B} 82(3). DOI: 10.1111/rssb.12369\\
Implemented in R package \texttt{flipscores}:\\
\url{https://cran.r-project.org/web/packages/flipscores/index.html}\strut \\
Development version: \url{https://github.com/livioivil/flipscores}

\textbf{Permutation regression review}:\\
- Winkler AM, Ridgway GR, Webster MA, Smith SM, Nichols TE (2014)
Permutation inference for the general linear model. \emph{NeuroImage}
92:381-397. \url{doi:10.1016/j.neuroimage.2014.01.060}

\end{document}
